# Generated by Django 5.0.4 on 2024-04-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aadi_app', '0004_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
